### PR TITLE
Changing activerecord dependencies to support rails 6.

### PR DESCRIPTION
**Pull request by ckozus**
This will make the gem compatible with Rails 6. 
We have already used on `missionhub-api`.

### CODE REVIEW

**Comment by soberstadt** [comment]
This uses a build matrix to test different versions of rails and ruby. Could you update the travis config to also test on rails 5?

**Comment by ckozus** [comment]
> This uses a build matrix to test different versions of rails and ruby. Could you update the travis config to also test on rails 6?

for sure! Should I create a new ticket for that?

**Comment by soberstadt** [comment]
No, I think that is fitting for this PR. If you are going to add rails 6 support, add testing for that :)

**Comment by ckozus** [comment]
@soberstadt do I need to use Appraisal to generate the different versions of the testing matrix? I see the ones used to test with different versions of sidekiq have comments saying they were automatically generated by Appraisal.

I don't see any notes about it on the README file either.

**Comment by soberstadt** [comment]
I think so. @Omicron7 do you have any words of wisdom to add rails 6?

**Comment by Omicron7** [comment]
I honestly don't remember. Looking at the code, it looks like I used Appraisals to test the 2 versions of sidekiq only (had to hook into them differently), never multiple versions for rails. It looks like travis was also testing different ruby versions.

I think you'll add another config section to the [Appraisals](https://github.com/CruGlobal/global-registry-bindings/blob/master/Appraisals) file that uses rails 6, then run `bundle exec appraisal generate` to add new gemfile, and add that to travis.yml.

**Pull request merged**
